name: expenses_tracker
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  powersync: ^1.2.2
  path_provider: ^2.0.12
  path: ^1.8.2
  logging: ^1.1.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.0
  http: ^1.1.0
  fl_chart: ^0.66.2
  uuid: ^4.3.3
  flutter_slidable: ^3.0.1
  internet_connection_checker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
