// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCIboJwfSa4cqVA8h0-CeyH6L52iU-eto',
    appId: '1:737618750285:web:d59f049d9d90fe9ce76504',
    messagingSenderId: '737618750285',
    projectId: 'expenses-tracker-45b12',
    authDomain: 'expenses-tracker-45b12.firebaseapp.com',
    storageBucket: 'expenses-tracker-45b12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSQem1V2sW6iVUGBf_FKUf4t_ok5o-Lg',
    appId: '1:737618750285:android:25f7a097dd75436be76504',
    messagingSenderId: '737618750285',
    projectId: 'expenses-tracker-45b12',
    storageBucket: 'expenses-tracker-45b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9DesVIWBjlHA75rhPnxoY7N_FF9Nj6s',
    appId: '1:737618750285:ios:d321a02ffc3881ede76504',
    messagingSenderId: '737618750285',
    projectId: 'expenses-tracker-45b12',
    storageBucket: 'expenses-tracker-45b12.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9DesVIWBjlHA75rhPnxoY7N_FF9Nj6s',
    appId: '1:737618750285:ios:64a219ba83552d78e76504',
    messagingSenderId: '737618750285',
    projectId: 'expenses-tracker-45b12',
    storageBucket: 'expenses-tracker-45b12.appspot.com',
    iosBundleId: 'com.example.expensesTracker.RunnerTests',
  );
}
